# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/plotly_tensor',
                'doc_host': 'https://neelnanda-io.github.io',
                'git_url': 'https://github.com/neelnanda-io/plotly_tensor',
                'lib_path': 'plotly_tensor'},
  'syms': {'plotly_tensor.core': {'plotly_tensor.core.foo': ('core.html#foo', 'plotly_tensor/core.py')}}}